INSERT INTO hero(hero_id, name)
VALUES (1, 'Barbarian'),
       (2, 'Moon Elf'),
       (3, 'Pyromancer'),
       (4, 'Shadow Thief'),
       (5, 'Monk'),
       (6, 'Paladin'),
       (7, 'Ninja'),
       (8, 'Treant'),
       (9, 'Cursed Pirate'),
       (10, 'Artificer'),
       (11, 'Seraph'),
       (12, 'Vampire Lord'),
       (13, 'Gunslinger'),
       (14, 'Samurai'),
       (15, 'Tactician'),
       (16, 'Huntress'),
       (17, 'Black Panther'),
       (18, 'Captain Marvel'),
       (19, 'Black Widow'),
       (20, 'Doctor Strange'),
       (21, 'Scarlet Witch'),
       (22, 'Loki'),
       (23, 'Thor'),
       (24, 'Spider-Man'),
       (25, 'Krampus'),
       (26, 'Santa')
ON CONFLICT (hero_id) DO NOTHING;
